name: motion_sensors_example
description: Demonstrates how to use the motion_sensors plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  motion_sensors:
    path: ../
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
