name: motion_sensors
description: Flutter plugin for accessing the Android and iOS accelerometer, gyroscope, magnetometer, and orientation sensors.
version: 0.1.0
homepage: https://github.com/zesage/motion_sensors

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: finaldev.motion_sensors
        pluginClass: MotionSensorsPlugin
      ios:
        pluginClass: MotionSensorsPlugin
